run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - misspell

linters-settings:
  errcheck:
    check-blank: false
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-dirs:
    - vendor
    - console
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
